name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Frontend Docker image
        run: docker build -t myapp-frontend -f ./frontend/Dockerfile ./frontend

  build-and-test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Backend Docker image
        run: docker build -t myapp-backend -f ./backend/Dockerfile ./backend
