name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Frontend image
        run: |
          docker build -t myapp-frontend ./frontend
          docker tag myapp-frontend mydockerhubusername/myapp-frontend:latest
          docker push mydockerhubusername/myapp-frontend:latest

      - name: Build and push Backend image
        run: |
          docker build -t myapp-backend ./backend
          docker tag myapp-backend mydockerhubusername/myapp-backend:latest
          docker push mydockerhubusername/myapp-backend:latest
